# Copyright 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: test-user
  namespace: rook-ceph
spec:
  store: my-store
  displayName: "Test User"
