# Copyright 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: ceph.cobaltcore.sap.com/v1alpha1
kind: RemoteCluster
metadata:
  name: external-arbiter
  namespace: external-arbiter
spec:
  # target namespace to deploy arbiter
  namespace: external-arbiter
  # reference to k8s secret with kubeconfig at the same namespace
  accesskeyRef:
    # name of the secret
    name: external-arbiter
    # key in provided secret
    key: "kubeconfig.yaml"
  # interval between running cluster check
  # 0 to disable
  checkInterval: 1m
  # remote client request timeout
  # 0 to disable
  timeout: 10s