---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ceph.cobaltcore.sap.com
  resources:
  - remotearbiters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ceph.cobaltcore.sap.com
  resources:
  - remotearbiters/finalizers
  verbs:
  - update
- apiGroups:
  - ceph.cobaltcore.sap.com
  resources:
  - remotearbiters/status
  verbs:
  - get
  - patch
  - update
