# Copyright 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0
---
{{ if .Values.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-selfsigned-issuer
  labels:
  {{- include "external-arbiter-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{ end }}