# Copyright 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0
---
{{ if .Values.useMonitoring }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-manager-metrics-monitor
  labels:
    control-plane: controller-manager
    {{- include "external-arbiter-operator.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: https # Ensure this is the name of the port that exposes HTTPS metrics
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        serverName: {{ .Release.Name }}-controller-manager-metrics-service.{{ .Release.Namespace }}
        {{ if .Values.useCertManager }}
        insecureSkipVerify: false
        ca:
          secret:
            name: metrics-server-cert
            key: ca.crt
        cert:
          secret:
            name: metrics-server-cert
            key: tls.crt
        keySecret:
          name: metrics-server-cert
          key: tls.key
        {{ else }}
        insecureSkipVerify: true
        {{ end }}
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: kubesample
{{ end }}