# Copyright 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0
---
{{ if .Values.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-metrics-cert
  labels:
  {{- include "external-arbiter-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ .Release.Name }}-metrics-service.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-metrics-service.{{ .Release.Namespace }}.svc.{{ .Values.cluster.domain }}
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-selfsigned-issuer
  secretName: {{ .Release.Name }}-metrics-server-cert
{{ end }}