# Copyright 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-controller-manager-metrics-service
  labels:
    control-plane: {{ .Release.Name }}-controller-manager
    {{- include "external-arbiter-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    - name: https
      port: {{ .Values.metricsService.port }}
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: {{ .Release.Name }}-controller-manager
    {{- include "external-arbiter-operator.selectorLabels" . | nindent 4 }}